[package]
name = "postcss"
version = "0.0.1"
description = "🚀 Fast and 100% API compatible postcss replacer"
authors = ["迷渡 <justjavac@gmail.com>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/justjavac/postcss-rs"
license = "MIT"
keywords = ["css", "syntax", "postcss", "parser", "ast"]

[dependencies]
fancy-regex = "0.7.1"
lazy_static = "1"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"
